export { default as CartPage } from "./CartPage";
export { default as HomePage } from "./HomePage";
export { default as LoginPage } from "./LoginPage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as PizzaPage } from "./PizzaPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as RegisterPage } from "./RegisterPage";
export { default as NavbarApp } from "../components/Navbar";
export { default as Footer } from "../components/Footer";
